name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - '**'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format
        run: |
          BRANCH_NAME="${GITHUB_REF##refs/heads/}"
          echo "🔎 Checking branch: $BRANCH_NAME"

          PATTERN='^(story|defect|hotfix)/[a-zA-Z][a-zA-Z0-9]*[0-9]US[0-9]+$'

          if [[ "$BRANCH_NAME" =~ $PATTERN ]]; then
            echo "✅ Branch name is valid."
            exit 0
          else
            echo "❌ Invalid branch name: '$BRANCH_NAME'"
            echo "Expected format: story|defect|hotfix/<ms_id>US<jira_number>"
            echo "Example: story/asin1329US12345"
            exit 1
          fi
